"""empty message

Revision ID: 3b307db938dd
Revises: a3ebf703eab9
Create Date: 2025-08-05 02:19:58.999608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b307db938dd'
down_revision = 'a3ebf703eab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sauce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('spice', sa.Enum('BAJO', 'POCO', 'MEDIO', 'ALTO', 'AGRESIVO', 'ARRANCA_GARGANTAS', name='spice'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assosiation_sauces',
    sa.Column('taco_id', sa.Integer(), nullable=True),
    sa.Column('sauce_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sauce_id'], ['sauce.id'], ),
    sa.ForeignKeyConstraint(['taco_id'], ['taco.id'], )
    )
    with op.batch_alter_table('taco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'protein', ['protein_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('protein_id')

    op.drop_table('assosiation_sauces')
    op.drop_table('sauce')
    op.drop_table('protein')
    # ### end Alembic commands ###
